extends Control

const stupidly_long_array_of_color_constants_why_has_god_abandoned_us_help = {
	#"aliceblue" : Color.aliceblue, 
	#"antiquewhite" : Color.antiquewhite, 
	#"aqua" : Color.aqua, 
	"aquamarine" : Color.aquamarine, 
	"azure" : Color.azure, 
	#"beige" : Color.beige, 
	"bisque" : Color.bisque, 
	#"black" : Color.black,
	"blanchedalmond" : Color.blanchedalmond, 
	#Color.blue, 
	"blueviolet" : Color.blueviolet, 
	"brown" : Color.brown, 
	"burlywood" : Color.burlywood, 
	"cadetblue" : Color.cadetblue, 
	#Color.chartreuse, 
	"chocolate" : Color.chocolate, 
	"coral" : Color.coral, 
	"cornflower" : Color.cornflower, 
	#"cornsilk" : Color.cornsilk, 
	"crimson" : Color.crimson, 
	#"cyan" : Color.cyan, 
	"darkblue" : Color.darkblue, 
	"darkcyan" : Color.darkcyan, 
	"darkgoldenrod" : Color.darkgoldenrod, 
	#"darkgray" : Color.darkgray, 
	"darkgreen" : Color.darkgreen, 
	"darkkhaki" : Color.darkkhaki, 
	"darkmagenta" : Color.darkmagenta, 
	"darkolivegreen" : Color.darkolivegreen, 
	"darkorange" : Color.darkorange, 
	"darkorchid" : Color.darkorchid, 
	"darkred" : Color.darkred, 
	"darksalmon" : Color.darksalmon, 
	"darkseagreen" : Color.darkseagreen, 
	"darkslateblue" : Color.darkslateblue, 
	"darkslategray" : Color.darkslategray, 
	"darkturquoise" : Color.darkturquoise, 
	"darkviolet" : Color.darkviolet, 
	"deeppink" : Color.deeppink, 
	"deepskyblue" : Color.deepskyblue, 
	#"dimgray" : Color.dimgray, 
	"dodgerblue" : Color.dodgerblue, 
	"firebrick" : Color.firebrick, 
	#"floralwhite" : Color.floralwhite, 
	"forestgreen" : Color.forestgreen, 
	"fuchsia" : Color.fuchsia, 
	#"gainsboro" : Color.gainsboro, 
	#"ghostwhite" : Color.ghostwrite,
	"gold" : Color.gold, 
	"goldenrod" : Color.goldenrod, 
	#"lightgray" : Color.lightgray,
	"lightgreen" : Color.lightgreen,
	"lightpink" : Color.lightpink, 
	"lightsalmon" : Color.lightsalmon,
	"lightseagreen" : Color.lightseagreen, 
	"lightskyblue" : Color.lightskyblue, 
	"lightslategray" : Color.lightslategray, 
	#"lightsteelblue" : Color.lightsteelblue, 
	"lightyellow" : Color.lightyellow,
	"lime" : Color.lime, 
	"limegreen" : Color.limegreen,
	#"linen" : Color.linen, 
	#"magenta" : Color.magenta, 
	"maroon" : Color.maroon, 
	"mediumaquamarine" : Color.mediumaquamarine, 
	"mediumblue" : Color.mediumblue, 
	"mediumorchid" : Color.mediumorchid, 
	"mediumpurple" : Color.mediumpurple, 
	"mediumseagreen" : Color.mediumseagreen, 
	"mediumslateblue" : Color.mediumslateblue, 
	"mediumspringgreen" : Color.mediumspringgreen, 
	"mediumturquoise" : Color.mediumturquoise, 
	"mediumvioletred" : Color.mediumvioletred, 
	"midnightblue" : Color.midnightblue, 
	#"mintcream" : Color.mintcream, 
	#"mistyrose" : Color.mistyrose, 
	"moccasin" : Color.moccasin,
	#"navajowhite" : Color.navajowhite, 
	#"navyblue" : Color.navyblue, 
	#"oldlace" : Color.oldlace, 
	"olive" : Color.olive, 
	"olivedrab" : Color.olivedrab, 
	"orange" : Color.orange, 
	"orangered" : Color.orangered, 
	"orchid" : Color.orchid, 
	"palegoldenrod" : Color.palegoldenrod, 
	"palegreen" : Color.palegreen, 
	"paleturquoise" : Color.paleturquoise, 
	"palevioletred" : Color.palevioletred, 
	#"papayawhip" : Color.papayawhip, 
	"peachpuff" : Color.peachpuff, 
	"peru" : Color.peru, 
	"pink" : Color.pink,
	"plum" : Color.plum, 
	"powderblue" : Color.powderblue, 
	"purple" : Color.purple, 
	"rebeccapurple" : Color.rebeccapurple, 
	#"red" : Color.red, 
	"rosybrown" : Color.rosybrown, 
	"royalblue" : Color.royalblue, 
	"saddlebrown" : Color.saddlebrown, 
	"salmon" : Color.salmon,
	"sandybrown" : Color.sandybrown,
	"seagreen" : Color.seagreen, 
	#"seashell" : Color.seashell,
	"sienna" : Color.sienna, 
	#"silver" : Color.silver, 
	"skyblue" : Color.skyblue, 
	"slateblue" : Color.slateblue,
	#"snow" : Color.snow,
	"springgreen" : Color.springgreen, 
	"steelblue" : Color.steelblue, 
	"tan" : Color.tan, 
	"teal" : Color.teal, 
	"thistle" : Color.thistle, 
	"tomato" : Color.tomato, 
	#"transparent" : Color.transparent, 
	"turquoise" : Color.turquoise, 
	"violet" : Color.violet, 
	#"webgray" : Color.webgray, 
	#"webgreen" : Color.webgreen, 
	"webmaroon" : Color.webmaroon, 
	"webpurple" : Color.webpurple, 
	"wheat" : Color.wheat, 
	#"white" : Color.white, 
	#"whitesmoke" : Color.whitesmoke, 
	#"yellow" : Color.yellow, 
	"yellowgreen" : Color.yellowgreen
}

func _ready():
	randomize()

func get_random_color() -> Color:
	var arr = stupidly_long_array_of_color_constants_why_has_god_abandoned_us_help.keys()
	arr.shuffle()
	#print(arr[0])
	return stupidly_long_array_of_color_constants_why_has_god_abandoned_us_help[arr[0]]
